### ISSUE TITLE
Windows 10 Compile error

### ISSUE THREAD

**Issue by huaijiuwow** [Titans-Project/BfaCore-Reforged#30]
Error compiling in VS2019 release mode.  C2079, C2664, C2679, LNK1181 are displayed.  
Cmake: 3.22.1  
boost：1.76
vs：2019
openssl：1.0.2O
mysql：5.7.18

**Comment by Nexon99** [comment]
Do you use all the software we provide on Discord (#Download) ?
You should not encounter any errors. 🤔

**Comment by ReyDonovan** [comment]
not support boost 1.76

**Comment by huaijiuwow** [comment]
ok,thanks



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 13, 2022 17:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Titans-Project/BfaCore-Reforged] Windows 10 Compile error (Issue#30)




 
not support boost 1.76

**Comment by fuzionproject** [comment]
will be fixed on the next update
