### ISSUE TITLE
Ubuntu Compile Error

### ISSUE THREAD

**Issue by Stalingradka** [Titans-Project/BfaCore-Reforged#31]
Building CXX object src/server/game/CMakeFiles/game.dir/cmake_pch.hxx.pch
In file included from <built-in>:1:
In file included from /BfaCore/source/build/src/server/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /BfaCore/source/src/server/game/PrecompiledHeaders/gamePCH.h:3:
In file included from /BfaCore/source/src/server/game/Entities/Creature/Creature.h:27:
In file included from /BfaCore/source/src/server/game/Maps/MapObject.h:22:
In file included from /BfaCore/source/src/server/game/Grids/Cells/Cell.h:26:
In file included from /BfaCore/source/src/server/game/Grids/GridDefines.h:22:
/BfaCore/source/src/server/game/Grids/NGrid.h:92:58: fatal error: cannot assign to non-static data member within const member function 'SetGridId'
        void SetGridId(const uint32 id) const { i_gridId = id; }
                                                ~~~~~~~~ ^
/BfaCore/source/src/server/game/Grids/NGrid.h:92:14: note: member function 'NGrid::SetGridId' is declared const here
        void SetGridId(const uint32 id) const { i_gridId = id; }
        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:64: src/server/game/CMakeFiles/game.dir/cmake_pch.hxx.pch] Error 1
make[1]: *** [CMakeFiles/Makefile2:1103: src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by fuzionproject** [comment]
contact me on discord  to get me some ss and entire errors list on virtual studio 2019

Frozen
#1935
