### ISSUE TITLE
I don't recommend this build.

### ISSUE THREAD

**Issue by Acid2020** [Titans-Project/BfaCore-Reforged#35]
Easy errors could not be corrected! In a few hours I fixed 200kb of errors only in the database! there is still a lot of work to be done on the core! although the authors will sell their clumsy hotfixes than do something! During this time that their assembly lives, it was already possible to bring to mind at least the old content, not to mention Bfa

**Comment by cooler-SAI** [comment]
keep your opinion with yours, please! it's issue place, not for feedbacks
